# required settings
[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# my settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 1024
max_test_rejects = 65536
seed = 1234

[invariant]
runs = 256
depth = 15
fail_on_revert = false

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 140
tab_width = 2
number_underscore = "thousands"
wrap_comments = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options