# required settings
[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# my settings
solc_version = "0.8.17"
optimizer = true
optimizer_runs = 200


[fmt]
line_length = 140
tab_width = 2
number_underscore = "thousands"
wrap_comments = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options